import Link from "next/link";
export const metadata = { title: "Terms — Impromptu" };

export default function Terms() {
  return (
    <div className="wrap doc">
      <p className="eyebrow">Terms</p>
      <h1>Free, open, and provided as-is.</h1>
      <p className="lede">Impromptu is a free, open-source tool released under the MIT licence. These terms describe what you may do with it and what it does not promise you.</p>
      <p className="stamp">Effective 22 September 2026 · Version 2.0.0</p>

      <h2>1. Agreement</h2>
      <p>By using Impromptu you accept these terms. If you do not accept them, do not use it. If you have an account you can delete it yourself at any time from Settings.</p>

      <h2>2. What the service is</h2>
      <p>Impromptu is a web application that suggests educational topics, displays a short reference definition, provides a notes area and a sixty-second timer, and — with an account and an active plan — records a one-minute speech, transcribes it and produces an automated grade and feedback. It is a practice aid. It provides no instruction, certification, assessment of record, or professional advice of any kind.</p>

      <h2>3. Accounts</h2>
      <p>An account is an email address you confirm, a public username and a password. You are responsible for keeping the password safe; it can be reset by email. One person per account. Do not pick a username that impersonates someone else. Accounts that abuse the service or the third-party APIs it depends on may be removed.</p>

      <h2>4. Cost and limits</h2>
      <p>Drawing topics, notes and the timer are free and need no account. Recording and grading require an account and are <strong>free during the beta</strong>, limited to <strong>three graded takes per calendar day (UTC)</strong>. Because each graded minute costs real money, a paid plan may be introduced later; if so you will be told by email at least thirty days before anything is charged, and nothing will ever be charged without you choosing to subscribe. One account per person.</p>

      <h2>5. Availability</h2>
      <p>Impromptu is a personal project: it may be changed, moved or taken offline at any time without notice. Export your data if you want a copy you control.</p>

      <h2>6. Licence</h2>
      <p>The source code is released under the MIT licence. You may use, copy, modify, distribute and sell it, including commercially, provided the copyright notice and licence text are retained. Full text is in the <a href="https://github.com/mattsinitiere/impromtu/blob/main/LICENSE" target="_blank" rel="noopener">LICENSE file</a>.</p>

      <h2>7. Your content</h2>
      <p>Your notes, recordings, transcripts and speeches are yours. You grant Impromptu only the licence needed to store and show them back to you. Audio is not retained. See the <Link href="/privacy">privacy page</Link>.</p>

      <h2>8. Third-party content and accuracy</h2>
      <p>Definitions are retrieved from Wikipedia under <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noopener">CC BY-SA 4.0</a>. Transcripts and grades are generated by OpenAI models.</p>
      <div className="callout">
        <p><strong>The grade is an opinion, not a measurement.</strong> Automated transcription mishears words and automated grading is inconsistent, sometimes wrong, and can be swayed by phrasing. Use it as a coach's note, not a score of record. Verify definitions before you present them; if you repeat something publicly, you own what you said.</p>
      </div>

      <h2>9. Acceptable use</h2>
      <p>Do not use Impromptu to break the law, to record anyone without their consent, to share an account, to create multiple accounts to get around the daily limit, or to disrupt the site or the services it depends on. Do not script the recording endpoint. Accounts that do may be closed.</p>

      <h2>10. No warranty</h2>
      <p>Impromptu is provided <strong>"as is", without warranty of any kind</strong>, express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose and non-infringement. There is no guarantee that it will be available, error-free, accurate, or that stored data will persist.</p>

      <h2>11. Limitation of liability</h2>
      <p>To the maximum extent permitted by law, the author is not liable for any indirect, incidental, special, consequential or exemplary damages arising from your use of or inability to use Impromptu — including lost notes or speeches, lost time, or any consequence of relying on a definition or grade it displayed. In any event, total liability is limited to the amount you paid in the three months before the claim, which during the beta is nothing.</p>

      <h2>12. Changes to these terms</h2>
      <p>These terms may be revised. The effective date above will change, and every revision is visible in the project's commit history. Continuing to use the application after a change means you accept the revised terms.</p>

      <h2>13. Governing law</h2>
      <p>These terms are governed by the laws of the State of Texas, United States, without regard to its conflict-of-law rules.</p>

      <h2>14. Contact</h2>
      <p>Questions about these terms go to the <Link href="/contact">contact page</Link>.</p>

      <div className="plain">
        <p>This document describes how the application actually behaves and is written in plain language on purpose. It is not legal advice. If Impromptu is deployed commercially or inside an organisation, have a lawyer review it first.</p>
      </div>
    </div>
  );
}
